set serveroutput on;

--------------------------Visitor User----------------------------
DECLARE nCount number;
BEGIN 
SELECT 
  count(*) into nCount 
FROM 
  ALL_USERS 
where 
  USERNAME = 'VISITOR';
IF(nCount > 0) THEN dbms_output.put_line('VISITOR USER ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'create user VISITOR identified by setsrfSDEdfsdfserfse42343';
EXECUTE IMMEDIATE 'GRANT CREATE SESSION,CONNECT TO VISITOR';
END IF;
EXCEPTION WHEN OTHERS THEN dbms_output.put_line(
  dbms_utility.format_error_backtrace
);
dbms_output.put_line(SQLERRM);
ROLLBACK;
RAISE;
COMMIT;
END;
/ 

--------------------------General Customer Role---------------------------
DECLARE
nCount number;
BEGIN
SELECT 
  count(*) into nCount 
FROM 
  DBA_ROLES 
where 
  ROLE = 'CUSTOMER_INFO6210';
IF(nCount > 0) 
THEN 
dbms_output.put_line('ROLE CUSTOMER_INFO6210 ALREADY EXISTS');
ELSE EXECUTE IMMEDIATE 'CREATE ROLE CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON TAGS TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON SUBSCRIPTIONS TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON STREET TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON STATE TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON PROPERTY_TYPE TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON LISTING_TAGS TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON LEASE_TYPE TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON AREA TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON CITY TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON ADDRESS TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON QUERY TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON OFFER TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON LISTING_STATUS TO CUSTOMER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON COMPLAINTS TO CUSTOMER_INFO6210';
COMMIT;
END IF;
END;

---------------------------General Poster Role------------------------------
DECLARE
nCount number;
BEGIN
SELECT 
  count(*) into nCount 
FROM 
  DBA_ROLES 
where 
  ROLE = 'POSTER_INFO6210';
IF(nCount > 0) THEN dbms_output.put_line(
  'ROLE POSTER_INFO6210 ALREADY EXISTS'
);
ELSE EXECUTE IMMEDIATE 'CREATE ROLE POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CONNECT TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON TAGS TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON STREET TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON STATE TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON CITY TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON ADDRESS TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT ON AREA TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON QUERY TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON PROPERTY_TYPE TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON POSTER TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON OFFER TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON LISTING_TAGS TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON LISTING_STATUS TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON LISTING TO POSTER_INFO6210';
EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE ON LEASE_TYPE TO POSTER_INFO6210';
COMMIT;
END IF;
END;